//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKI_QLTTQuocAnh.DS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BKI_QLTTQuocAnh;Initial Catalog=BKI_QLTTQuocAnh;Persist Security Info" +
            "=True;User ID=sa;Password=sa123456")]
        public string BKI_QLTTQuocAnhConnectionString {
            get {
                return ((string)(this["BKI_QLTTQuocAnhConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=BKI_QLTTQuocAnh;User ID=sa;Password=sa")]
        public string BKI_QLTTQuocAnhConnectionString1 {
            get {
                return ((string)(this["BKI_QLTTQuocAnhConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\TNT;Initial Catalog=BKI_QLTTQuocAnh;Persist Security Info=True;User" +
            " ID=sa;Password=sa")]
        public string BKI_QLTTQuocAnhConnectionString2 {
            get {
                return ((string)(this["BKI_QLTTQuocAnhConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HNC\\TNT;Initial Catalog=BKI_QLTTQuocAnh;User ID=sa;Password=sa")]
        public string BKI_QLTTQuocAnhConnectionString3 {
            get {
                return ((string)(this["BKI_QLTTQuocAnhConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATATSRV;Initial Catalog=master;Persist Security Info=True;User ID=bk" +
            "index;Password=bkindex")]
        public string masterConnectionString {
            get {
                return ((string)(this["masterConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATATSRV;Initial Catalog=BKI_QLTTQuocAnh;Persist Security Info=True;U" +
            "ser ID=bkindex;Password=bkindex")]
        public string BKI_QLTTQuocAnhConnectionString4 {
            get {
                return ((string)(this["BKI_QLTTQuocAnhConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=QUYETNT-PC\\SQLEXPRESS;Initial Catalog=BKI_QLTTQuocAnh;User ID=sa;Pass" +
            "word=sa")]
        public string BKI_QLTTQuocAnhConnectionString5 {
            get {
                return ((string)(this["BKI_QLTTQuocAnhConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LENOVO-PC\\SQLEXPRESS;Initial Catalog=BKI_QLTTQuocAnh;Persist Security" +
            " Info=True;User ID=sa;Password=123456")]
        public string BKI_QLTTQuocAnhConnectionString6 {
            get {
                return ((string)(this["BKI_QLTTQuocAnhConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQL2008;Initial Catalog=BKI_QLTTQuocAnh;Persist Security Info=True;" +
            "User ID=sa;Password=sa")]
        public string BKI_QLTTQuocAnhConnectionString7 {
            get {
                return ((string)(this["BKI_QLTTQuocAnhConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LENOVO-PC\\SQLEXPRESS;Initial Catalog=BKI_QLTTQuocAnh_2;Persist Securi" +
            "ty Info=True;User ID=sa;Password=123456")]
        public string BKI_QLTTQuocAnh_2ConnectionString {
            get {
                return ((string)(this["BKI_QLTTQuocAnh_2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TUND\\SQLEXPRESS;Initial Catalog=QuanLyTTQuocAnh;User ID=sa;Password=s" +
            "a")]
        public string QuanLyTTQuocAnhConnectionString {
            get {
                return ((string)(this["QuanLyTTQuocAnhConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HAIHD\\SQLEXPRESS;Initial Catalog=QuanLyTTQuocAnh;User ID=sa;Password=" +
            "123456")]
        public string QuanLyTTQuocAnhConnectionString1 {
            get {
                return ((string)(this["QuanLyTTQuocAnhConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HAIHD\\SQLEXPRESS;Initial Catalog=QuanLyTTQuocAnhVer2;User ID=sa;Passw" +
            "ord=123456")]
        public string QuanLyTTQuocAnhVer2ConnectionString {
            get {
                return ((string)(this["QuanLyTTQuocAnhVer2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NGV\\SQL2005;Initial Catalog=QuanLyTTQuocAnh;Persist Security Info=Tru" +
            "e;User ID=sa;Password=sa")]
        public string QuanLyTTQuocAnhConnectionString2 {
            get {
                return ((string)(this["QuanLyTTQuocAnhConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HAPPYMAN\\SQLEXPRESS;Initial Catalog=QuanLyTTQuocAnh;Persist Security " +
            "Info=True;User ID=sa;Password=sa")]
        public string QuanLyTTQuocAnhConnectionString3 {
            get {
                return ((string)(this["QuanLyTTQuocAnhConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HAPPYMAN\\SQLEXPRESS;Initial Catalog=QuanLyTTQuocAnh_Final;Persist Sec" +
            "urity Info=True;User ID=sa;Password=sa")]
        public string QuanLyTTQuocAnh_FinalConnectionString {
            get {
                return ((string)(this["QuanLyTTQuocAnh_FinalConnectionString"]));
            }
        }
    }
}
