///************************************************
/// Generated by: PhongPN
/// Date: 15/07/2015 06:30:58
/// Goal: Create User Service Class for DM_NGACH_DAI
///************************************************
/// <summary>
/// Create User Service Class for DM_NGACH_DAI
/// </summary>

using System;
using BKI_QLTTQuocAnh.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;

namespace BKI_QLTTQuocAnh.US{

public class US_DM_NGACH_DAI : US_Object
{
	private const string c_TableName = "DM_NGACH_DAI";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_NGACH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NGACH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NGACH"] = value;
		}
	}

	public bool IsID_NGACHNull()	{
		return pm_objDR.IsNull("ID_NGACH");
	}

	public void SetID_NGACHNull() {
		pm_objDR["ID_NGACH"] = System.Convert.DBNull;
	}

	public decimal dcID_DAI 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DAI", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DAI"] = value;
		}
	}

	public bool IsID_DAINull()	{
		return pm_objDR.IsNull("ID_DAI");
	}

	public void SetID_DAINull() {
		pm_objDR["ID_DAI"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_NGACH_DAI() 
	{
		pm_objDS = new DS_DM_NGACH_DAI();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_NGACH_DAI(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_NGACH_DAI(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_NGACH_DAI();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
