///************************************************
/// Generated by: PhongPN
/// Date: 09/07/2015 03:34:17
/// Goal: Create User Service Class for DM_DAI_HOC_PHAN
///************************************************
/// <summary>
/// Create User Service Class for DM_DAI_HOC_PHAN
/// </summary>

namespace BKI_QLTTQuocAnh.US
{
    using BKI_QLTTQuocAnh.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using System;


public class US_DM_DAI_HOC_PHAN : US_Object
{
	private const string c_TableName = "DM_DAI_HOC_PHAN";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_PHONG_DAI 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_PHONG_DAI", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_PHONG_DAI"] = value;
		}
	}

	public bool IsID_PHONG_DAINull()	{
		return pm_objDR.IsNull("ID_PHONG_DAI");
	}

	public void SetID_PHONG_DAINull() {
		pm_objDR["ID_PHONG_DAI"] = System.Convert.DBNull;
	}

	public decimal dcID_HOC_PHAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_HOC_PHAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_HOC_PHAN"] = value;
		}
	}

	public bool IsID_HOC_PHANNull()	{
		return pm_objDR.IsNull("ID_HOC_PHAN");
	}

	public void SetID_HOC_PHANNull() {
		pm_objDR["ID_HOC_PHAN"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_DAI_HOC_PHAN() 
	{
		pm_objDS = new DS_DM_DAI_HOC_PHAN();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_DAI_HOC_PHAN(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_DAI_HOC_PHAN(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_DAI_HOC_PHAN();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
}
}
