///************************************************
/// Generated by: PhongPN
/// Date: 15/07/2015 06:34:03
/// Goal: Create User Service Class for DM_NGHIEP_VU_MON_HOC
///************************************************
/// <summary>
/// Create User Service Class for DM_NGHIEP_VU_MON_HOC
/// </summary>

using System;
using BKI_QLTTQuocAnh.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_QLTTQuocAnh.US{

public class US_DM_NGHIEP_VU_MON_HOC : US_Object
{
	private const string c_TableName = "DM_NGHIEP_VU_MON_HOC";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_NGHIEP_VU 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NGHIEP_VU", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NGHIEP_VU"] = value;
		}
	}

	public bool IsID_NGHIEP_VUNull()	{
		return pm_objDR.IsNull("ID_NGHIEP_VU");
	}

	public void SetID_NGHIEP_VUNull() {
		pm_objDR["ID_NGHIEP_VU"] = System.Convert.DBNull;
	}

	public decimal dcID_MON_HOC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_MON_HOC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_MON_HOC"] = value;
		}
	}

	public bool IsID_MON_HOCNull()	{
		return pm_objDR.IsNull("ID_MON_HOC");
	}

	public void SetID_MON_HOCNull() {
		pm_objDR["ID_MON_HOC"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_NGHIEP_VU_MON_HOC() 
	{
		pm_objDS = new DS_DM_NGHIEP_VU_MON_HOC();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_NGHIEP_VU_MON_HOC(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_NGHIEP_VU_MON_HOC(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_NGHIEP_VU_MON_HOC();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
