///************************************************
/// Generated by: NGOCTQ
/// Date: 13/07/2015 11:39:21
/// Goal: Create User Service Class for V_DAI_HOC_PHAN
///************************************************
/// <summary>
/// Create User Service Class for V_DAI_HOC_PHAN
/// </summary>

using System;
using BKI_QLTTQuocAnh.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_QLTTQuocAnh.US{

public class US_V_DAI_HOC_PHAN : US_Object
{
	private const string c_TableName = "V_DAI_HOC_PHAN";
#region "Public Properties"
	public string strMA_DAI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_DAI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_DAI"] = value;
		}
	}

	public bool IsMA_DAINull() 
	{
		return pm_objDR.IsNull("MA_DAI");
	}

	public void SetMA_DAINull() {
		pm_objDR["MA_DAI"] = System.Convert.DBNull;
	}

	public string strTEN_DAI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_DAI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_DAI"] = value;
		}
	}

	public bool IsTEN_DAINull() 
	{
		return pm_objDR.IsNull("TEN_DAI");
	}

	public void SetTEN_DAINull() {
		pm_objDR["TEN_DAI"] = System.Convert.DBNull;
	}

	public string strMA_HOC_PHAN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_HOC_PHAN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_HOC_PHAN"] = value;
		}
	}

	public bool IsMA_HOC_PHANNull() 
	{
		return pm_objDR.IsNull("MA_HOC_PHAN");
	}

	public void SetMA_HOC_PHANNull() {
		pm_objDR["MA_HOC_PHAN"] = System.Convert.DBNull;
	}

	public string strTEN_HOC_PHAN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_HOC_PHAN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_HOC_PHAN"] = value;
		}
	}

	public bool IsTEN_HOC_PHANNull() 
	{
		return pm_objDR.IsNull("TEN_HOC_PHAN");
	}

	public void SetTEN_HOC_PHANNull() {
		pm_objDR["TEN_HOC_PHAN"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_DAI_HOC_PHAN() 
	{
		pm_objDS = new DS_V_DAI_HOC_PHAN();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_DAI_HOC_PHAN(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_DAI_HOC_PHAN(decimal i_dbID) 
	{
		pm_objDS = new DS_V_DAI_HOC_PHAN();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
