///************************************************
/// Generated by: NGOCTQ
/// Date: 13/07/2015 11:02:55
/// Goal: Create User Service Class for V_PHONG_DAI
///************************************************
/// <summary>
/// Create User Service Class for V_PHONG_DAI
/// </summary>

using System;
using BKI_QLTTQuocAnh.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_QLTTQuocAnh.US{

public class US_V_PHONG_DAI : US_Object
{
	private const string c_TableName = "V_PHONG_DAI";
#region "Public Properties"
	public string strMA_DON_VI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_DON_VI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_DON_VI"] = value;
		}
	}

	public bool IsMA_DON_VINull() 
	{
		return pm_objDR.IsNull("MA_DON_VI");
	}

	public void SetMA_DON_VINull() {
		pm_objDR["MA_DON_VI"] = System.Convert.DBNull;
	}

	public string strTEN_DON_VI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_DON_VI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_DON_VI"] = value;
		}
	}

	public bool IsTEN_DON_VINull() 
	{
		return pm_objDR.IsNull("TEN_DON_VI");
	}

	public void SetTEN_DON_VINull() {
		pm_objDR["TEN_DON_VI"] = System.Convert.DBNull;
	}

	public string strMA_DAI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_DAI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_DAI"] = value;
		}
	}

	public bool IsMA_DAINull() 
	{
		return pm_objDR.IsNull("MA_DAI");
	}

	public void SetMA_DAINull() {
		pm_objDR["MA_DAI"] = System.Convert.DBNull;
	}

	public string strTEN_DAI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_DAI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_DAI"] = value;
		}
	}

	public bool IsTEN_DAINull() 
	{
		return pm_objDR.IsNull("TEN_DAI");
	}

	public void SetTEN_DAINull() {
		pm_objDR["TEN_DAI"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_PHONG_DAI() 
	{
		pm_objDS = new DS_V_PHONG_DAI();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_PHONG_DAI(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_PHONG_DAI(decimal i_dbID) 
	{
		pm_objDS = new DS_V_PHONG_DAI();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
