///************************************************
/// Generated by: NGOCTQ
/// Date: 12/07/2015 11:07:58
/// Goal: Create User Service Class for V_GD_LOP_MON
///************************************************
/// <summary>
/// Create User Service Class for V_GD_LOP_MON
/// </summary>

using System;
using BKI_QLTTQuocAnh.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_QLTTQuocAnh.US{

public class US_V_GD_LOP_MON : US_Object
{
	private const string c_TableName = "V_GD_LOP_MON";
#region "Public Properties"
	public string strMA_LOP_HOC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_LOP_HOC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_LOP_HOC"] = value;
		}
	}

	public bool IsMA_LOP_HOCNull() 
	{
		return pm_objDR.IsNull("MA_LOP_HOC");
	}

	public void SetMA_LOP_HOCNull() {
		pm_objDR["MA_LOP_HOC"] = System.Convert.DBNull;
	}

	public string strMA_MON_HOC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_MON_HOC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_MON_HOC"] = value;
		}
	}

	public bool IsMA_MON_HOCNull() 
	{
		return pm_objDR.IsNull("MA_MON_HOC");
	}

	public void SetMA_MON_HOCNull() {
		pm_objDR["MA_MON_HOC"] = System.Convert.DBNull;
	}

	public string strTEN_MON_HOC 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_MON_HOC", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_MON_HOC"] = value;
		}
	}

	public bool IsTEN_MON_HOCNull() 
	{
		return pm_objDR.IsNull("TEN_MON_HOC");
	}

	public void SetTEN_MON_HOCNull() {
		pm_objDR["TEN_MON_HOC"] = System.Convert.DBNull;
	}

	public string strDON_VI_GIANG_DAY 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DON_VI_GIANG_DAY", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DON_VI_GIANG_DAY"] = value;
		}
	}

	public bool IsDON_VI_GIANG_DAYNull() 
	{
		return pm_objDR.IsNull("DON_VI_GIANG_DAY");
	}

	public void SetDON_VI_GIANG_DAYNull() {
		pm_objDR["DON_VI_GIANG_DAY"] = System.Convert.DBNull;
	}

	public DateTime datTHOI_GIAN
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "THOI_GIAN", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["THOI_GIAN"] = value;
		}
	}

	public bool IsTHOI_GIANNull()
	{
		return pm_objDR.IsNull("THOI_GIAN");
	}

	public void SetTHOI_GIANNull()
	{
		pm_objDR["THOI_GIAN"] = System.Convert.DBNull;
	}

	public string strDIA_DIEM 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DIA_DIEM", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DIA_DIEM"] = value;
		}
	}

	public bool IsDIA_DIEMNull() 
	{
		return pm_objDR.IsNull("DIA_DIEM");
	}

	public void SetDIA_DIEMNull() {
		pm_objDR["DIA_DIEM"] = System.Convert.DBNull;
	}

	public decimal dcSO_LUONG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_LUONG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_LUONG"] = value;
		}
	}

	public bool IsSO_LUONGNull()	{
		return pm_objDR.IsNull("SO_LUONG");
	}

	public void SetSO_LUONGNull() {
		pm_objDR["SO_LUONG"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_GD_LOP_MON() 
	{
		pm_objDS = new DS_V_GD_LOP_MON();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_GD_LOP_MON(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_GD_LOP_MON(decimal i_dbID) 
	{
		pm_objDS = new DS_V_GD_LOP_MON();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
