///************************************************
/// Generated by: PhongPN
/// Date: 13/07/2015 01:55:19
/// Goal: Create Form for DM_MON_HOC
///************************************************


using System;
using System.Data;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

using IP.Core.IPCommon;
using IP.Core.IPException;
using IP.Core.IPData;
using IP.Core.IPUserService;
using IP.Core.IPSystemAdmin;

using BKI_QLTTQuocAnh.US;
using BKI_QLTTQuocAnh.DS;
using BKI_QLTTQuocAnh.DS.CDBNames;
using BKI_QLTTQuocAnh.DanhMuc;

using C1.Win.C1FlexGrid;
using DevExpress.XtraGrid.Views.Grid;

namespace BKI_QLTTQuocAnh
{



	public class f101_danh_muc_mon_hoc : System.Windows.Forms.Form
	{
		internal System.Windows.Forms.ImageList ImageList;
        internal System.Windows.Forms.Panel m_pnl_out_place_dm;
		internal SIS.Controls.Button.SiSButton m_cmd_delete;
		internal SIS.Controls.Button.SiSButton m_cmd_update;
		internal SIS.Controls.Button.SiSButton m_cmd_insert;
		internal SIS.Controls.Button.SiSButton m_cmd_exit;
        internal SIS.Controls.Button.SiSButton m_cmd_view;
        private FlowLayoutPanel flowLayoutPanel1;
        private Label label1;
        private DevExpress.XtraEditors.PanelControl panelControl1;
        private DevExpress.XtraGrid.GridControl m_grc;
        private DevExpress.XtraGrid.Views.Grid.GridView gridView1;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn1;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn2;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn3;
        private DevExpress.XtraGrid.Columns.GridColumn gridColumn4;
		private System.ComponentModel.IContainer components;

		public f101_danh_muc_mon_hoc()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

			//
			// TODO: Add any constructor code after InitializeComponent call
			//
            //format_controls();
		}

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if(components != null)
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(f101_danh_muc_mon_hoc));
            this.ImageList = new System.Windows.Forms.ImageList(this.components);
            this.m_pnl_out_place_dm = new System.Windows.Forms.Panel();
            this.m_cmd_insert = new SIS.Controls.Button.SiSButton();
            this.m_cmd_update = new SIS.Controls.Button.SiSButton();
            this.m_cmd_view = new SIS.Controls.Button.SiSButton();
            this.m_cmd_delete = new SIS.Controls.Button.SiSButton();
            this.m_cmd_exit = new SIS.Controls.Button.SiSButton();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.label1 = new System.Windows.Forms.Label();
            this.panelControl1 = new DevExpress.XtraEditors.PanelControl();
            this.m_grc = new DevExpress.XtraGrid.GridControl();
            this.gridView1 = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.gridColumn4 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn1 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn2 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.gridColumn3 = new DevExpress.XtraGrid.Columns.GridColumn();
            this.m_pnl_out_place_dm.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.panelControl1)).BeginInit();
            this.panelControl1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_grc)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // ImageList
            // 
            this.ImageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("ImageList.ImageStream")));
            this.ImageList.TransparentColor = System.Drawing.Color.Transparent;
            this.ImageList.Images.SetKeyName(0, "");
            this.ImageList.Images.SetKeyName(1, "");
            this.ImageList.Images.SetKeyName(2, "");
            this.ImageList.Images.SetKeyName(3, "");
            this.ImageList.Images.SetKeyName(4, "");
            this.ImageList.Images.SetKeyName(5, "");
            this.ImageList.Images.SetKeyName(6, "");
            this.ImageList.Images.SetKeyName(7, "");
            this.ImageList.Images.SetKeyName(8, "");
            this.ImageList.Images.SetKeyName(9, "");
            this.ImageList.Images.SetKeyName(10, "");
            this.ImageList.Images.SetKeyName(11, "");
            this.ImageList.Images.SetKeyName(12, "");
            this.ImageList.Images.SetKeyName(13, "");
            this.ImageList.Images.SetKeyName(14, "");
            this.ImageList.Images.SetKeyName(15, "");
            this.ImageList.Images.SetKeyName(16, "");
            this.ImageList.Images.SetKeyName(17, "");
            this.ImageList.Images.SetKeyName(18, "");
            this.ImageList.Images.SetKeyName(19, "");
            this.ImageList.Images.SetKeyName(20, "");
            this.ImageList.Images.SetKeyName(21, "");
            // 
            // m_pnl_out_place_dm
            // 
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_insert);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_update);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_view);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_delete);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_exit);
            this.m_pnl_out_place_dm.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.m_pnl_out_place_dm.Location = new System.Drawing.Point(0, 373);
            this.m_pnl_out_place_dm.Name = "m_pnl_out_place_dm";
            this.m_pnl_out_place_dm.Padding = new System.Windows.Forms.Padding(4);
            this.m_pnl_out_place_dm.Size = new System.Drawing.Size(689, 36);
            this.m_pnl_out_place_dm.TabIndex = 19;
            // 
            // m_cmd_insert
            // 
            this.m_cmd_insert.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_insert.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_insert.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_insert.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_insert.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_insert.ImageIndex = 2;
            this.m_cmd_insert.ImageList = this.ImageList;
            this.m_cmd_insert.Location = new System.Drawing.Point(333, 4);
            this.m_cmd_insert.Name = "m_cmd_insert";
            this.m_cmd_insert.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_insert.TabIndex = 12;
            this.m_cmd_insert.Text = "&Thêm";
            // 
            // m_cmd_update
            // 
            this.m_cmd_update.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_update.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_update.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_update.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_update.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_update.ImageIndex = 3;
            this.m_cmd_update.ImageList = this.ImageList;
            this.m_cmd_update.Location = new System.Drawing.Point(421, 4);
            this.m_cmd_update.Name = "m_cmd_update";
            this.m_cmd_update.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_update.TabIndex = 13;
            this.m_cmd_update.Text = "&Sửa";
            // 
            // m_cmd_view
            // 
            this.m_cmd_view.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_view.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_view.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_view.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_view.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_view.ImageIndex = 18;
            this.m_cmd_view.ImageList = this.ImageList;
            this.m_cmd_view.Location = new System.Drawing.Point(4, 4);
            this.m_cmd_view.Name = "m_cmd_view";
            this.m_cmd_view.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_view.TabIndex = 21;
            this.m_cmd_view.Text = "Xem";
            // 
            // m_cmd_delete
            // 
            this.m_cmd_delete.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_delete.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_delete.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_delete.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_delete.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_delete.ImageIndex = 4;
            this.m_cmd_delete.ImageList = this.ImageList;
            this.m_cmd_delete.Location = new System.Drawing.Point(509, 4);
            this.m_cmd_delete.Name = "m_cmd_delete";
            this.m_cmd_delete.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_delete.TabIndex = 14;
            this.m_cmd_delete.Text = "&Xoá";
            // 
            // m_cmd_exit
            // 
            this.m_cmd_exit.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_exit.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_exit.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_exit.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_exit.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_exit.ImageIndex = 12;
            this.m_cmd_exit.ImageList = this.ImageList;
            this.m_cmd_exit.Location = new System.Drawing.Point(597, 4);
            this.m_cmd_exit.Name = "m_cmd_exit";
            this.m_cmd_exit.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_exit.TabIndex = 11;
            this.m_cmd_exit.Text = "Thoát (Esc)";
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.Location = new System.Drawing.Point(270, 28);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new System.Drawing.Size(28, 16);
            this.flowLayoutPanel1.TabIndex = 24;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Times New Roman", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.label1.ForeColor = System.Drawing.Color.Maroon;
            this.label1.Location = new System.Drawing.Point(239, 9);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(182, 24);
            this.label1.TabIndex = 23;
            this.label1.Text = "Danh mục môn học";
            // 
            // panelControl1
            // 
            this.panelControl1.Controls.Add(this.label1);
            this.panelControl1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelControl1.Location = new System.Drawing.Point(0, 0);
            this.panelControl1.Name = "panelControl1";
            this.panelControl1.Size = new System.Drawing.Size(689, 44);
            this.panelControl1.TabIndex = 25;
            // 
            // m_grc
            // 
            this.m_grc.Cursor = System.Windows.Forms.Cursors.Default;
            this.m_grc.Dock = System.Windows.Forms.DockStyle.Fill;
            this.m_grc.Location = new System.Drawing.Point(0, 44);
            this.m_grc.MainView = this.gridView1;
            this.m_grc.Name = "m_grc";
            this.m_grc.Size = new System.Drawing.Size(689, 329);
            this.m_grc.TabIndex = 26;
            this.m_grc.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.gridView1});
            // 
            // gridView1
            // 
            this.gridView1.Columns.AddRange(new DevExpress.XtraGrid.Columns.GridColumn[] {
            this.gridColumn4,
            this.gridColumn1,
            this.gridColumn2,
            this.gridColumn3});
            this.gridView1.GridControl = this.m_grc;
            this.gridView1.Name = "gridView1";
            this.gridView1.PopupMenuShowing += new DevExpress.XtraGrid.Views.Grid.PopupMenuShowingEventHandler(this.gridView1_PopupMenuShowing);
            this.gridView1.CustomUnboundColumnData += new DevExpress.XtraGrid.Views.Base.CustomColumnDataEventHandler(this.gridView1_CustomUnboundColumnData);
            // 
            // gridColumn4
            // 
            this.gridColumn4.Caption = "STT";
            this.gridColumn4.FieldName = "gridColumn4";
            this.gridColumn4.Name = "gridColumn4";
            this.gridColumn4.UnboundType = DevExpress.Data.UnboundColumnType.Integer;
            this.gridColumn4.Visible = true;
            this.gridColumn4.VisibleIndex = 0;
            // 
            // gridColumn1
            // 
            this.gridColumn1.Caption = "Mã môn học";
            this.gridColumn1.FieldName = "MA_MON_HOC";
            this.gridColumn1.Name = "gridColumn1";
            this.gridColumn1.Visible = true;
            this.gridColumn1.VisibleIndex = 1;
            // 
            // gridColumn2
            // 
            this.gridColumn2.Caption = "Tên môn học";
            this.gridColumn2.FieldName = "TEN_MON_HOC";
            this.gridColumn2.Name = "gridColumn2";
            this.gridColumn2.Visible = true;
            this.gridColumn2.VisibleIndex = 2;
            // 
            // gridColumn3
            // 
            this.gridColumn3.Caption = "Đơn vị giảng dạy";
            this.gridColumn3.FieldName = "DON_VI_GIANG_DAY";
            this.gridColumn3.Name = "gridColumn3";
            this.gridColumn3.Visible = true;
            this.gridColumn3.VisibleIndex = 3;
            // 
            // f101_danh_muc_mon_hoc
            // 
            this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
            this.ClientSize = new System.Drawing.Size(689, 409);
            this.Controls.Add(this.m_grc);
            this.Controls.Add(this.panelControl1);
            this.Controls.Add(this.flowLayoutPanel1);
            this.Controls.Add(this.m_pnl_out_place_dm);
            this.Name = "f101_danh_muc_mon_hoc";
            this.Text = "F101 - Danh mục môn học";
            this.Load += new System.EventHandler(this.f101_danh_muc_mon_hoc_Load);
            this.m_pnl_out_place_dm.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.panelControl1)).EndInit();
            this.panelControl1.ResumeLayout(false);
            this.panelControl1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_grc)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridView1)).EndInit();
            this.ResumeLayout(false);

		}
		#endregion

		#region Public Interface
		public void display(){			
			this.ShowDialog();
		}
		#endregion

		#region Data Structure
		private enum e_col_Number{
			DON_VI_GIANG_DAY = 3
,TEN_MON_HOC = 2
,MA_MON_HOC = 1

		}			
		#endregion

		#region Members
		ITransferDataRow m_obj_trans;		
		DS_DM_MON_HOC m_ds = new DS_DM_MON_HOC();
		US_DM_MON_HOC m_us = new US_DM_MON_HOC();
		#endregion

		#region Private Methods
        //private void format_controls(){
        //    CControlFormat.setFormStyle(this, new CAppContext_201());
        //    CControlFormat.setC1FlexFormat(m_fg);
        //    CGridUtils.AddSave_Excel_Handlers(m_fg);
        //                CGridUtils.AddSearch_Handlers(m_fg);
        //    set_define_events();
        //    this.KeyPreview = true;		
        //}
        //private void set_initial_form_load(){						
        //    m_obj_trans = get_trans_object(m_fg);
        //    load_data_2_grid();		
        //}	
        //private ITransferDataRow get_trans_object(C1.Win.C1FlexGrid.C1FlexGrid i_fg){
        //    Hashtable v_htb = new Hashtable();
        //    v_htb.Add(DM_MON_HOC.DON_VI_GIANG_DAY, e_col_Number.DON_VI_GIANG_DAY);
        //    v_htb.Add(DM_MON_HOC.TEN_MON_HOC, e_col_Number.TEN_MON_HOC);
        //    v_htb.Add(DM_MON_HOC.MA_MON_HOC, e_col_Number.MA_MON_HOC);
									
        //    ITransferDataRow v_obj_trans = new CC1TransferDataRow(i_fg,v_htb,m_ds.DM_MON_HOC.NewRow());
        //    return v_obj_trans;			
        //}
        //private void load_data_2_grid()
        //{
        //    m_ds = new DS_DM_MON_HOC();
        //    m_us.FillDataset(m_ds, " where ten_mon_hoc LIKE N'%" + m_txt_tim_kiem.Text.Trim().ToLower() + "%' or ma_mon_hoc LIKE '%" + m_txt_tim_kiem.Text.Trim().ToLower() + "%'");
        //    m_fg.Redraw = false;
        //    CGridUtils.Dataset2C1Grid(m_ds, m_fg, m_obj_trans);
        //    m_fg.Redraw = true;
        //}
        //private void grid2us_object(US_DM_MON_HOC i_us
        //    , int i_grid_row) {
        //    DataRow v_dr;
        //    v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
        //    m_obj_trans.GridRow2DataRow(i_grid_row,v_dr);
        //    i_us.DataRow2Me(v_dr);
        //}

	
        //private void us_object2grid(US_DM_MON_HOC i_us
        //    , int i_grid_row) {
        //    DataRow v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
        //    i_us.Me2DataRow(v_dr);
        //    m_obj_trans.DataRow2GridRow(v_dr, i_grid_row);
        //}


        //private void insert_dm_mon_hoc(){
        //    f101_danh_muc_mon_hoc_de v_fDE = new f101_danh_muc_mon_hoc_de();
        //    v_fDE.display_for_insert();
        //    load_data_2_grid();
        //}

        //private void update_dm_mon_hoc(){			
        //    if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
        //    if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;			
        //    grid2us_object(m_us, m_fg.Row);
        //    f101_danh_muc_mon_hoc_de v_fDE = new f101_danh_muc_mon_hoc_de();
        //    v_fDE.display_for_update(m_us);
        //    load_data_2_grid();
        //}
				
        //private void delete_dm_mon_hoc(){
        //    if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
        //    if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
        //    if (BaseMessages.askUser_DataCouldBeDeleted(8) != BaseMessages.IsDataCouldBeDeleted.CouldBeDeleted)  return;
        //    US_DM_MON_HOC v_us = new US_DM_MON_HOC();
        //    grid2us_object(v_us, m_fg.Row);
        //    try {			
        //        v_us.BeginTransaction();    											
        //        v_us.Delete();                      								
        //        v_us.CommitTransaction();
        //        m_fg.Rows.Remove(m_fg.Row);				
        //    }
        //    catch (Exception v_e) {
        //        v_us.Rollback();
        //        CDBExceptionHandler v_objErrHandler = new CDBExceptionHandler(v_e,
        //            new CDBClientDBExceptionInterpret());
        //        v_objErrHandler.showErrorMessage();
        //    }
        //}

        //private void view_dm_mon_hoc(){			
        //    if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
        //    if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
        //    grid2us_object(m_us, m_fg.Row);
        //    f101_danh_muc_mon_hoc_de v_fDE = new f101_danh_muc_mon_hoc_de();
        //    v_fDE.display_for_view(m_us);
        //}
        //private void set_define_events(){
        //    m_cmd_exit.Click += new EventHandler(m_cmd_exit_Click);
        //    m_cmd_insert.Click += new EventHandler(m_cmd_insert_Click);
        //    m_cmd_update.Click += new EventHandler(m_cmd_update_Click);
        //    m_cmd_delete.Click += new EventHandler(m_cmd_delete_Click);
        //    m_cmd_view.Click += new EventHandler(m_cmd_view_Click);
        //}
		#endregion

//
		//
		//		EVENT HANLDERS
		//
		//
		private void f101_danh_muc_mon_hoc_Load(object sender, System.EventArgs e) {
			load_data_2_grid();
			}
        private void load_data_2_grid(){//Hiển thị khi mới laod form

         US_DUNG_CHUNG v_us = new US_DUNG_CHUNG();
            DataSet v_ds = new DataSet();
            v_ds.Tables.Add(new DataTable());
            v_us.FillDatasetWithTableName(v_ds, "DM_MON_HOC");
            m_grc.DataSource = v_ds.Tables[0];
        }

        private void gridView1_CustomUnboundColumnData(object sender, DevExpress.XtraGrid.Views.Base.CustomColumnDataEventArgs e)
        {
            if (e.IsGetData)
                e.Value = e.ListSourceRowIndex + 1;
        }

        private void gridView1_PopupMenuShowing(object sender, DevExpress.XtraGrid.Views.Grid.PopupMenuShowingEventArgs e)
        {
            GridView view = sender as GridView;
            // Check whether a row is right-clicked.
            if (e.MenuType == DevExpress.XtraGrid.Views.Grid.GridMenuType.Row)
            {
                int rowHandle = e.HitInfo.RowHandle;
                // Delete existing menu items, if any.
                e.Menu.Items.Clear();
                // Add a submenu with a single menu item.
                e.Menu.Items.Add(WinFormControls.CreateRowSubMenu(view, rowHandle));
            }
        }
		
		

        //private void m_cmd_exit_Click(object sender, EventArgs e) {
        //    try{
        //        this.Close();
        //    }
        //    catch (Exception v_e){
        //        CSystemLog_301.ExceptionHandle(v_e);
        //    }
        //}

        //private void m_cmd_insert_Click(object sender, EventArgs e) {
        //    try{
        //        insert_dm_mon_hoc();
        //    }
        //    catch (Exception v_e){
        //        CSystemLog_301.ExceptionHandle(v_e);
        //    }
        //}
        ////Sửa dữ liệu 
        //private void m_cmd_update_Click(object sender, EventArgs e) {
        //    try{
        //        update_dm_mon_hoc();
        //    }
        //    catch (Exception v_e){
        //        CSystemLog_301.ExceptionHandle(v_e);
        //    }
        //}

        //private void m_cmd_delete_Click(object sender, EventArgs e) {
        //    try{
        //        delete_dm_mon_hoc();
        //    }
        //    catch (Exception v_e){
        //        CSystemLog_301.ExceptionHandle(v_e);
        //    }
        //}

        //private void m_cmd_view_Click(object sender, EventArgs e) {
        //    try{
        //        view_dm_mon_hoc();
        //    }
        //    catch (Exception v_e){
        //        CSystemLog_301.ExceptionHandle(v_e);
        //    }
        //}

       

	}
}

