///////////////////////////////////////////////////////////////////////////
// Description: Data Access class for the table 'DM_HOC_PHAN'
// Generated by LLBLGen v1.21.2003.712 Final on: 09 Tháng Bảy 2015, 2:58:50 CH
// Because the Base Class already implements IDispose, this class doesn't.
///////////////////////////////////////////////////////////////////////////
using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;

namespace DAO_TAO_NOI_BOLLBL
{
	/// <summary>
	/// Purpose: Data Access class for the table 'DM_HOC_PHAN'.
	/// </summary>
	public class DM_HOC_PHAN : DBInteractionBase
	{
		#region Class Member Declarations
			private SqlInt32		_sO_LUONG_YEU_CAU;
			private SqlDecimal		_iD;
			private SqlString		_bAT_BUOC_YN, _mA_HOC_PHAN, _tEN_HOC_PHAN;
		#endregion


		/// <summary>
		/// Purpose: Class constructor.
		/// </summary>
		public DM_HOC_PHAN()
		{
			// Nothing for now.
		}


		/// <summary>
		/// Purpose: Insert method. This method will insert one new row into the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>MA_HOC_PHAN</LI>
		///		 <LI>TEN_HOC_PHAN</LI>
		///		 <LI>SO_LUONG_YEU_CAU. May be SqlInt32.Null</LI>
		///		 <LI>BAT_BUOC_YN. May be SqlString.Null</LI>
		/// </UL>
		/// Properties set after a succesful call of this method: 
		/// <UL>
		///		 <LI>ID</LI>
		/// </UL>
		/// </remarks>
		public override bool Insert()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[pr_DM_HOC_PHAN_Insert]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@MA_HOC_PHAN", SqlDbType.NVarChar, 35, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _mA_HOC_PHAN));
				cmdToExecute.Parameters.Add(new SqlParameter("@TEN_HOC_PHAN", SqlDbType.NVarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _tEN_HOC_PHAN));
				cmdToExecute.Parameters.Add(new SqlParameter("@SO_LUONG_YEU_CAU", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, _sO_LUONG_YEU_CAU));
				cmdToExecute.Parameters.Add(new SqlParameter("@BAT_BUOC_YN", SqlDbType.NVarChar, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _bAT_BUOC_YN));
				cmdToExecute.Parameters.Add(new SqlParameter("@ID", SqlDbType.Decimal, 9, ParameterDirection.Output, false, 18, 1, "", DataRowVersion.Proposed, _iD));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				_iD = (Decimal)cmdToExecute.Parameters["@ID"].Value;
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("DM_HOC_PHAN::Insert::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Update method. This method will Update one existing row in the database.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID</LI>
		///		 <LI>MA_HOC_PHAN</LI>
		///		 <LI>TEN_HOC_PHAN</LI>
		///		 <LI>SO_LUONG_YEU_CAU. May be SqlInt32.Null</LI>
		///		 <LI>BAT_BUOC_YN. May be SqlString.Null</LI>
		/// </UL>
		/// </remarks>
		public override bool Update()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[pr_DM_HOC_PHAN_Update]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@ID", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD));
				cmdToExecute.Parameters.Add(new SqlParameter("@MA_HOC_PHAN", SqlDbType.NVarChar, 35, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _mA_HOC_PHAN));
				cmdToExecute.Parameters.Add(new SqlParameter("@TEN_HOC_PHAN", SqlDbType.NVarChar, 50, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _tEN_HOC_PHAN));
				cmdToExecute.Parameters.Add(new SqlParameter("@SO_LUONG_YEU_CAU", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, _sO_LUONG_YEU_CAU));
				cmdToExecute.Parameters.Add(new SqlParameter("@BAT_BUOC_YN", SqlDbType.NVarChar, 1, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, _bAT_BUOC_YN));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("DM_HOC_PHAN::Update::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Delete method. This method will Delete one existing row in the database, based on the Primary Key.
		/// </summary>
		/// <returns>True if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID</LI>
		/// </UL>
		/// </remarks>
		public override bool Delete()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[pr_DM_HOC_PHAN_Delete]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@ID", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				_rowsAffected = cmdToExecute.ExecuteNonQuery();
				return true;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("DM_HOC_PHAN::Delete::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
			}
		}


		/// <summary>
		/// Purpose: Select method. This method will Select one existing row from the database, based on the Primary Key.
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// Properties needed for this method: 
		/// <UL>
		///		 <LI>ID</LI>
		/// </UL>
		///		 <LI>ID</LI>
		///		 <LI>MA_HOC_PHAN</LI>
		///		 <LI>TEN_HOC_PHAN</LI>
		///		 <LI>SO_LUONG_YEU_CAU</LI>
		///		 <LI>BAT_BUOC_YN</LI>
		/// Will fill all properties corresponding with a field in the table with the value of the row selected.
		/// </remarks>
		public override DataTable SelectOne()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[pr_DM_HOC_PHAN_SelectOne]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable toReturn = new DataTable("DM_HOC_PHAN");
			SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{
				cmdToExecute.Parameters.Add(new SqlParameter("@ID", SqlDbType.Decimal, 9, ParameterDirection.Input, false, 18, 1, "", DataRowVersion.Proposed, _iD));

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				adapter.Fill(toReturn);
				if(toReturn.Rows.Count > 0)
				{
					_iD = (Decimal)toReturn.Rows[0]["ID"];
					_mA_HOC_PHAN = (string)toReturn.Rows[0]["MA_HOC_PHAN"];
					_tEN_HOC_PHAN = (string)toReturn.Rows[0]["TEN_HOC_PHAN"];
					_sO_LUONG_YEU_CAU = toReturn.Rows[0]["SO_LUONG_YEU_CAU"] == System.DBNull.Value ? SqlInt32.Null : (Int32)toReturn.Rows[0]["SO_LUONG_YEU_CAU"];
					_bAT_BUOC_YN = toReturn.Rows[0]["BAT_BUOC_YN"] == System.DBNull.Value ? SqlString.Null : (string)toReturn.Rows[0]["BAT_BUOC_YN"];
				}
				return toReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("DM_HOC_PHAN::SelectOne::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
				adapter.Dispose();
			}
		}


		/// <summary>
		/// Purpose: SelectAll method. This method will Select all rows from the table.
		/// </summary>
		/// <returns>DataTable object if succeeded, otherwise an Exception is thrown. </returns>
		/// <remarks>
		/// </remarks>
		public override DataTable SelectAll()
		{
			SqlCommand	cmdToExecute = new SqlCommand();
			cmdToExecute.CommandText = "dbo.[pr_DM_HOC_PHAN_SelectAll]";
			cmdToExecute.CommandType = CommandType.StoredProcedure;
			DataTable toReturn = new DataTable("DM_HOC_PHAN");
			SqlDataAdapter adapter = new SqlDataAdapter(cmdToExecute);

			// Use base class' connection object
			cmdToExecute.Connection = _mainConnection;

			try
			{

				if(_mainConnectionIsCreatedLocal)
				{
					// Open connection.
					_mainConnection.Open();
				}
				else
				{
					if(_mainConnectionProvider.IsTransactionPending)
					{
						cmdToExecute.Transaction = _mainConnectionProvider.CurrentTransaction;
					}
				}

				// Execute query.
				adapter.Fill(toReturn);
				return toReturn;
			}
			catch(Exception ex)
			{
				// some error occured. Bubble it to caller and encapsulate Exception object
				throw new Exception("DM_HOC_PHAN::SelectAll::Error occured.", ex);
			}
			finally
			{
				if(_mainConnectionIsCreatedLocal)
				{
					// Close connection.
					_mainConnection.Close();
				}
				cmdToExecute.Dispose();
				adapter.Dispose();
			}
		}


		#region Class Property Declarations
		public SqlDecimal ID
		{
			get
			{
				return _iD;
			}
			set
			{
				SqlDecimal iDTmp = (SqlDecimal)value;
				if(iDTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("ID", "ID can't be NULL");
				}
				_iD = value;
			}
		}


		public SqlString MA_HOC_PHAN
		{
			get
			{
				return _mA_HOC_PHAN;
			}
			set
			{
				SqlString mA_HOC_PHANTmp = (SqlString)value;
				if(mA_HOC_PHANTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("MA_HOC_PHAN", "MA_HOC_PHAN can't be NULL");
				}
				_mA_HOC_PHAN = value;
			}
		}


		public SqlString TEN_HOC_PHAN
		{
			get
			{
				return _tEN_HOC_PHAN;
			}
			set
			{
				SqlString tEN_HOC_PHANTmp = (SqlString)value;
				if(tEN_HOC_PHANTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("TEN_HOC_PHAN", "TEN_HOC_PHAN can't be NULL");
				}
				_tEN_HOC_PHAN = value;
			}
		}


		public SqlInt32 SO_LUONG_YEU_CAU
		{
			get
			{
				return _sO_LUONG_YEU_CAU;
			}
			set
			{
				SqlInt32 sO_LUONG_YEU_CAUTmp = (SqlInt32)value;
				if(sO_LUONG_YEU_CAUTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("SO_LUONG_YEU_CAU", "SO_LUONG_YEU_CAU can't be NULL");
				}
				_sO_LUONG_YEU_CAU = value;
			}
		}


		public SqlString BAT_BUOC_YN
		{
			get
			{
				return _bAT_BUOC_YN;
			}
			set
			{
				SqlString bAT_BUOC_YNTmp = (SqlString)value;
				if(bAT_BUOC_YNTmp.IsNull)
				{
					throw new ArgumentOutOfRangeException("BAT_BUOC_YN", "BAT_BUOC_YN can't be NULL");
				}
				_bAT_BUOC_YN = value;
			}
		}
		#endregion
	}
}
