///************************************************
/// Generated by: tund
/// Date: 21/07/2015 01:36:08
/// Goal: Create User Service Class for DM_VERSION_MON_HOC
///************************************************
/// <summary>
/// Create User Service Class for DM_VERSION_MON_HOC
/// </summary>

using System;
using BKI_DTNB.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_DTNB.US{

public class US_DM_VERSION_MON_HOC : US_Object
{
	private const string c_TableName = "DM_VERSION_MON_HOC";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_MON_HOC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_MON_HOC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_MON_HOC"] = value;
		}
	}

	public bool IsID_MON_HOCNull()	{
		return pm_objDR.IsNull("ID_MON_HOC");
	}

	public void SetID_MON_HOCNull() {
		pm_objDR["ID_MON_HOC"] = System.Convert.DBNull;
	}

	public string strMA_VERSION 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_VERSION", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_VERSION"] = value;
		}
	}

	public bool IsMA_VERSIONNull() 
	{
		return pm_objDR.IsNull("MA_VERSION");
	}

	public void SetMA_VERSIONNull() {
		pm_objDR["MA_VERSION"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_VERSION_MON_HOC() 
	{
		pm_objDS = new DS_DM_VERSION_MON_HOC();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_VERSION_MON_HOC(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_VERSION_MON_HOC(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_VERSION_MON_HOC();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
