///************************************************
/// Generated by: PhongPN
/// Date: 09/07/2015 03:34:57
/// Goal: Create User Service Class for DM_NGACH
///************************************************
/// <summary>
/// Create User Service Class for DM_NGACH
/// </summary>

namespace AuctionUS
{
using AuctionDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using System;


public class US_DM_NGACH : US_Object
{
	private const string c_TableName = "DM_NGACH";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strMA_NGACH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_NGACH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_NGACH"] = value;
		}
	}

	public bool IsMA_NGACHNull() 
	{
		return pm_objDR.IsNull("MA_NGACH");
	}

	public void SetMA_NGACHNull() {
		pm_objDR["MA_NGACH"] = System.Convert.DBNull;
	}

	public string strTEN_NGACH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_NGACH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_NGACH"] = value;
		}
	}

	public bool IsTEN_NGACHNull() 
	{
		return pm_objDR.IsNull("TEN_NGACH");
	}

	public void SetTEN_NGACHNull() {
		pm_objDR["TEN_NGACH"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_NGACH() 
	{
		pm_objDS = new DS_DM_NGACH();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_NGACH(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_NGACH(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_NGACH();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
}
}
